### ISSUE TITLE
Input output_path is required

### ISSUE THREAD

**Issue by blytheaw** [xo-energy/action-octopus-build-information#2]
Happy to have found this action, as I was just about to write this from scratch!

The README seems to indicate that output_path is optional, and if omitted, no json files will be written. It looks like this is not the case and a file creation will be attempted regardless of if this input is provided or not. This results in an error "##[error]The "path" argument must be one of type string, Buffer, or URL. Received type undefined".

I'm happy to submit a PR for this if you are accepting contributions.

**Comment by wjrogers** [comment]
You're right, obvious oversight there! Thanks for the report. I will fix it shortly.
