### ISSUE TITLE
Getting non-default space when space input not configured

### ISSUE THREAD

**Issue by blytheaw** [xo-energy/action-octopus-build-information#26]
Hello,

With the latest release, we are getting a non-default space from the action when we don't specify the space action input or environment variable. We have 30+ repositories relying on the default space behavior and this seems to be a regression. 

I looked through the code some and haven't been able to figure out where the bug is. It seems the only way this could happen is if the octopusSpace input is not in fact `null` when the input is not provided.

Appreciate a quick resolution on this. Thank you!

**Comment by blytheaw** [comment]
Update: It looks like core.getInput returns an empty string if it isn't set, so the null check in getSpace is not being triggered.

https://github.com/actions/toolkit/blob/master/packages/core/src/core.ts#L69

**Comment by wjrogers** [comment]
@blytheaw I think I misunderstood the bug at first. I saw how the default check would never be triggered, and I fixed it so it is triggered for any false-y `octopus_space` input. But you're saying you got a non-default space? Can you share what your space was named? Can a space have an empty name?

**Comment by blytheaw** [comment]
We have the following spaces:
- ID: Spaces-1, Name: RNM Deployments (Default)
- ID: Spaces-2, Name: RNM Configuration

Somehow we are getting Spaces-2 detected without specifying OCTOPUS_SPACE environment variable or the octopus_space input. Looking closer at the original code, I'm not sure how it is getting returned.

**Comment by wjrogers** [comment]
I figured it out. I am using `pickBy` and `defaultsAll` to prepare the inputs, which means that false-y input values get removed from the `inputs` object. So, the `spaceName` parameter is actually `undefined`, and Octopus Space objects don't have a `Slug` property, so in fact `item.Slug === search`, and it returns the first space in the list. I will try to get this right this time and push a fix shortly.

**Comment by wjrogers** [comment]
@blytheaw thank you for reporting this!

**Comment by blytheaw** [comment]
No problem, thanks for the quick fix!

Austin Blythe
________________________________


​
Austin Blythe
Software Developer
Main: 972.560.4000
RightNow Media | The Mission of the Church Matters
RightNow Media @ Work | Better at Home. Better at Work.
RightNow Events | Conferences to Encourage Christians
